import type { Metadata } from 'next';
import Link from 'next/link';
import { Breadcrumbs } from '@/components/layout/breadcrumbs';
import { getEnv } from '@/lib/env';

const pageTitle = 'Terms of Service';
const pageDescription =
  'Read the Terms of Service for KnowYourEmoji. Learn about the rules and guidelines for using our emoji interpretation platform and AI-powered tools.';

/**
 * Generate metadata for the terms page including canonical URL
 */
export function generateMetadata(): Metadata {
  const env = getEnv();
  const pageUrl = `${env.appUrl}/terms`;

  return {
    title: `${pageTitle} | ${env.appName}`,
    description: pageDescription,
    alternates: {
      canonical: pageUrl,
    },
    openGraph: {
      type: 'website',
      locale: 'en_US',
      url: pageUrl,
      siteName: env.appName,
      title: `${pageTitle} | ${env.appName}`,
      description: pageDescription,
      images: [
        {
          url: `${env.appUrl}/og-image.png`,
          width: 1200,
          height: 630,
          alt: `${pageTitle} | ${env.appName}`,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: `${pageTitle} | ${env.appName}`,
      description: pageDescription,
      images: [`${env.appUrl}/og-image.png`],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
  };
}

const breadcrumbItems = [{ label: 'Home', href: '/' }, { label: 'Terms of Service' }];

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <section className="bg-gradient-to-b from-blue-50 to-white dark:from-gray-900 dark:to-gray-800 py-12 md:py-16">
        <div className="container mx-auto px-4 max-w-4xl">
          <Breadcrumbs items={breadcrumbItems} className="mb-6" />

          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 dark:text-white mb-6 text-center">
            Terms of Service
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 text-center max-w-2xl mx-auto">
            Please read these terms carefully before using KnowYourEmoji.
          </p>
        </div>
      </section>

      <section className="py-16 bg-white dark:bg-gray-900">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="prose prose-lg dark:prose-invert max-w-none space-y-12">
            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                By accessing and using KnowYourEmoji (&quot;the Service&quot;), you agree to be
                bound by these Terms of Service. If you do not agree to these terms, please do not
                use the Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                2. Description of Service
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                KnowYourEmoji provides emoji interpretation and analysis tools, including an
                AI-powered message interpreter. The Service offers context-aware emoji meanings,
                platform differences, and generational nuance explanations.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                3. Use of the Service
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed mb-4">
                You agree to use the Service only for lawful purposes and in accordance with these
                Terms. You agree not to:
              </p>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2">
                <li>Use the Service in any way that violates applicable laws or regulations</li>
                <li>Attempt to interfere with or disrupt the Service or its infrastructure</li>
                <li>Use automated systems to access the Service beyond normal usage patterns</li>
                <li>Attempt to bypass rate limits or other usage restrictions</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                4. AI Interpreter
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The AI-powered interpreter provides suggested interpretations of emoji usage. These
                interpretations are generated by artificial intelligence and should be considered as
                suggestions, not definitive meanings. We do not guarantee the accuracy of any
                interpretation provided.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                5. Intellectual Property
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The Service and its original content, features, and functionality are owned by
                KnowYourEmoji. The Service is open source and available under the terms of its
                repository license on{' '}
                <Link
                  href="https://github.com/marc-aurele-besner/knowyouremoji.com"
                  className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  GitHub
                </Link>
                .
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                6. Disclaimer of Warranties
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The Service is provided &quot;as is&quot; and &quot;as available&quot; without
                warranties of any kind, either express or implied. We do not warrant that the
                Service will be uninterrupted, secure, or error-free.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                7. Limitation of Liability
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                In no event shall KnowYourEmoji be liable for any indirect, incidental, special,
                consequential, or punitive damages resulting from your use of or inability to use
                the Service.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                8. Changes to Terms
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                We reserve the right to modify these terms at any time. We will notify users of
                significant changes by updating the date at the bottom of this page. Continued use
                of the Service after changes constitutes acceptance of the new terms.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">9. Contact</h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                If you have any questions about these Terms of Service, please reach out through our{' '}
                <Link
                  href="https://github.com/marc-aurele-besner/knowyouremoji.com/issues"
                  className="text-blue-600 hover:text-blue-800 dark:text-blue-400 dark:hover:text-blue-300"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  GitHub Issues
                </Link>
                .
              </p>
            </div>

            <p className="text-sm text-gray-500 dark:text-gray-400 pt-8 border-t border-gray-200 dark:border-gray-700">
              Last updated: March 2026
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
