#!/usr/bin/env bun
/**
 * Plan 250 new deep-tier emoji combos across 10 emoji-family batches (23-32).
 * Each entry is hand-curated. The generator consumes the JSON this script emits.
 *
 * Usage: bun run scripts/plan-batch-23-32.ts
 * Output: scripts/batch-23-32-plan.json
 */
import fs from 'fs';
import path from 'path';
import type { EmojiComboCategoryName } from '../src/types/combo';

export type Family =
  | 'hearts-love'
  | 'smileys-emotion'
  | 'hands-body'
  | 'animals'
  | 'food-drink'
  | 'travel-places'
  | 'sports-music'
  | 'weather-nature'
  | 'objects-tech'
  | 'symbols-effects';

export interface ComboPlanEntry {
  /** URL slug; must be unique across existing 150 + these 250 combos. */
  slug: string;
  /** The literal emoji combination string, e.g. "💕✨". */
  combo: string;
  /** Slugs of the emojis in this combo (≥2 for deep tier). */
  emojis: [string, string] | [string, string, string];
  /** Display name, e.g. "Two Hearts Sparkle". */
  name: string;
  /** Combo category (drives content archetype). */
  category: EmojiComboCategoryName;
  /** Emoji family — used to bucket into 10 commits + 10 PR sections. */
  family: Family;
  /** 0..2 — rotates within-family content variants to defeat boilerplate. */
  variant: 0 | 1 | 2;
  /** 60..95 — popularity hint for the combo (used by generator for `popularity`). */
  popularity: number;
  /** 2..4 short tags; generator may append 1-2 more from a per-family pool. */
  tags: string[];
}

// --- Existing-slug collision guard ---
const existingCombosDir = path.join(process.cwd(), 'src', 'data', 'combos');
const existingSlugs = new Set<string>();
for (const f of fs.readdirSync(existingCombosDir).filter((f) => f.endsWith('.json'))) {
  const json = JSON.parse(fs.readFileSync(path.join(existingCombosDir, f), 'utf-8'));
  if (typeof json.slug === 'string') existingSlugs.add(json.slug);
}

const PLAN: ComboPlanEntry[] = [
  // ──────────────────────────────────────────────────────────────────
  // FAMILY 1: Hearts & Love — 25 combos
  //   relationship 12 / flirting 10 / emotion 3
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'red-heart-kiss-mark',
    combo: '❤️💋',
    emojis: ['red-heart', 'kiss-mark'],
    name: 'Heart Kiss',
    category: 'flirting',
    family: 'hearts-love',
    variant: 0,
    popularity: 88,
    tags: ['love', 'kiss', 'romance'],
  },
  {
    slug: 'two-hearts-sparkle',
    combo: '💕✨',
    emojis: ['two-hearts', 'sparkles'],
    name: 'Two Hearts Sparkle',
    category: 'relationship',
    family: 'hearts-love',
    variant: 1,
    popularity: 84,
    tags: ['love', 'sparkle', 'cute'],
  },
  {
    slug: 'mending-heart-crying',
    combo: '❤️‍🩹😢',
    emojis: ['mending-heart', 'crying-face'],
    name: 'Mending Heart Crying',
    category: 'emotion',
    family: 'hearts-love',
    variant: 2,
    popularity: 81,
    tags: ['healing', 'crying', 'tender'],
  },
  {
    slug: 'heart-on-fire-flame',
    combo: '❤️‍🔥🔥',
    emojis: ['heart-on-fire', 'fire'],
    name: 'Heart On Fire Flame',
    category: 'flirting',
    family: 'hearts-love',
    variant: 0,
    popularity: 86,
    tags: ['passion', 'burning', 'love'],
  },
  {
    slug: 'broken-heart-pray',
    combo: '💔🙏',
    emojis: ['broken-heart', 'folded-hands'],
    name: 'Broken Heart Pray',
    category: 'relationship',
    family: 'hearts-love',
    variant: 1,
    popularity: 79,
    tags: ['sad', 'hope', 'healing'],
  },
  {
    slug: 'heart-arrow-cupid',
    combo: '💘🏹',
    emojis: ['heart-with-arrow', 'bow-and-arrow'],
    name: 'Cupid Shot',
    category: 'flirting',
    family: 'hearts-love',
    variant: 2,
    popularity: 82,
    tags: ['cupid', 'match', 'romance'],
  },
  {
    slug: 'purple-heart-blue-heart',
    combo: '💜💙',
    emojis: ['purple-heart', 'blue-heart'],
    name: 'Purple Blue Hearts',
    category: 'relationship',
    family: 'hearts-love',
    variant: 0,
    popularity: 78,
    tags: ['support', 'ally', 'kindness'],
  },
  {
    slug: 'hand-heart-red-heart',
    combo: '🫶❤️',
    emojis: ['hand-heart', 'red-heart'],
    name: 'Hand On Heart',
    category: 'relationship',
    family: 'hearts-love',
    variant: 1,
    popularity: 87,
    tags: ['warmth', 'love', 'sentiment'],
  },
  {
    slug: 'white-heart-black-heart',
    combo: '🤍🖤',
    emojis: ['white-heart', 'black-heart'],
    name: 'White Black Hearts',
    category: 'relationship',
    family: 'hearts-love',
    variant: 2,
    popularity: 75,
    tags: ['contrast', 'duo', 'pair'],
  },
  {
    slug: 'sparkling-heart-revolving',
    combo: '💖💞',
    emojis: ['sparkling-heart', 'revolving-hearts'],
    name: 'Sparkling Revolving Hearts',
    category: 'flirting',
    family: 'hearts-love',
    variant: 0,
    popularity: 80,
    tags: ['sparkle', 'love', 'spinning'],
  },
  {
    slug: 'beating-heart-red-heart',
    combo: '💓❤️',
    emojis: ['beating-heart', 'red-heart'],
    name: 'Beating Heart',
    category: 'flirting',
    family: 'hearts-love',
    variant: 1,
    popularity: 83,
    tags: ['heartbeat', 'love', 'pulse'],
  },
  {
    slug: 'love-letter-kiss',
    combo: '💌💋',
    emojis: ['love-letter', 'kiss-mark'],
    name: 'Love Letter Kiss',
    category: 'flirting',
    family: 'hearts-love',
    variant: 2,
    popularity: 85,
    tags: ['letter', 'romance', 'secret'],
  },
  {
    slug: 'pink-heart-red-heart',
    combo: '🩷❤️',
    emojis: ['pink-heart', 'red-heart'],
    name: 'Pink And Red Hearts',
    category: 'relationship',
    family: 'hearts-love',
    variant: 0,
    popularity: 77,
    tags: ['soft', 'love', 'pair'],
  },
  {
    slug: 'orange-heart-yellow-heart',
    combo: '🧡💛',
    emojis: ['orange-heart', 'yellow-heart'],
    name: 'Orange Yellow Hearts',
    category: 'relationship',
    family: 'hearts-love',
    variant: 1,
    popularity: 74,
    tags: ['warm', 'sunny', 'friendship'],
  },
  {
    slug: 'green-heart-clover',
    combo: '💚🍀',
    emojis: ['green-heart', 'four-leaf-clover'],
    name: 'Green Heart Luck',
    category: 'relationship',
    family: 'hearts-love',
    variant: 2,
    popularity: 76,
    tags: ['luck', 'love', 'irish'],
  },
  {
    slug: 'two-hearts-eye',
    combo: '💕👀',
    emojis: ['two-hearts', 'eyes'],
    name: 'Two Hearts Eyes',
    category: 'flirting',
    family: 'hearts-love',
    variant: 0,
    popularity: 79,
    tags: ['shy', 'admire', 'look'],
  },
  {
    slug: 'heart-on-fire-100',
    combo: '❤️‍🔥💯',
    emojis: ['heart-on-fire', 'hundred-points'],
    name: 'Heart On Fire Real',
    category: 'emotion',
    family: 'hearts-love',
    variant: 1,
    popularity: 81,
    tags: ['intense', 'real', 'love'],
  },
  {
    slug: 'kiss-mark-wink',
    combo: '💋😉',
    emojis: ['kiss-mark', 'winking-face'],
    name: 'Kiss Wink',
    category: 'flirting',
    family: 'hearts-love',
    variant: 2,
    popularity: 84,
    tags: ['flirty', 'wink', 'kiss'],
  },
  {
    slug: 'red-heart-bouquet',
    combo: '❤️💐',
    emojis: ['red-heart', 'bouquet'],
    name: 'Heart Bouquet',
    category: 'relationship',
    family: 'hearts-love',
    variant: 0,
    popularity: 82,
    tags: ['gift', 'love', 'flowers'],
  },
  {
    slug: 'sparkling-heart-smiling',
    combo: '💖😊',
    emojis: ['sparkling-heart', 'smiling-face-with-smiling-eyes'],
    name: 'Sparkling Smile',
    category: 'emotion',
    family: 'hearts-love',
    variant: 1,
    popularity: 80,
    tags: ['warm', 'happy', 'glow'],
  },
  {
    slug: 'blue-heart-purple-heart',
    combo: '💙💜',
    emojis: ['blue-heart', 'purple-heart'],
    name: 'Blue Purple Hearts',
    category: 'relationship',
    family: 'hearts-love',
    variant: 2,
    popularity: 73,
    tags: ['cool', 'soft', 'tonal'],
  },
  {
    slug: 'heart-decoration-rose',
    combo: '💟🌹',
    emojis: ['heart-decoration', 'rose'],
    name: 'Heart Decoration Rose',
    category: 'relationship',
    family: 'hearts-love',
    variant: 0,
    popularity: 78,
    tags: ['classic', 'love', 'floral'],
  },
  {
    slug: 'revolving-hearts-eye',
    combo: '💞👀',
    emojis: ['revolving-hearts', 'eyes'],
    name: 'Revolving Hearts Eyes',
    category: 'flirting',
    family: 'hearts-love',
    variant: 1,
    popularity: 76,
    tags: ['love', 'looking', 'soft'],
  },
  {
    slug: 'mending-heart-bandage',
    combo: '❤️‍🩹🩹',
    emojis: ['mending-heart', 'adhesive-bandage'],
    name: 'Mending Heart Bandage',
    category: 'emotion',
    family: 'hearts-love',
    variant: 2,
    popularity: 79,
    tags: ['healing', 'recover', 'care'],
  },
  {
    slug: 'red-heart-cherry-blossom',
    combo: '❤️🌸',
    emojis: ['red-heart', 'cherry-blossom'],
    name: 'Heart Cherry Blossom',
    category: 'relationship',
    family: 'hearts-love',
    variant: 0,
    popularity: 77,
    tags: ['spring', 'soft', 'romantic'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 2: Smileys & Emotion Faces — 25 combos
  //   emotion 14 / reaction 6 / humor 5
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'face-screaming-crying',
    combo: '😱😭',
    emojis: ['face-screaming-in-fear', 'loudly-crying-face'],
    name: 'Screaming Crying',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 84,
    tags: ['drama', 'over-the-top', 'shock'],
  },
  {
    slug: 'mind-blown-sparkles',
    combo: '🤯✨',
    emojis: ['exploding-head', 'sparkles'],
    name: 'Mind Blown Sparkles',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 87,
    tags: ['wow', 'amazed', 'reaction'],
  },
  {
    slug: 'clown-shocked',
    combo: '🤡😲',
    emojis: ['clown-face', 'astonished-face'],
    name: 'Clown Shocked',
    category: 'humor',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 79,
    tags: ['clown', 'shock', 'silly'],
  },
  {
    slug: 'skull-pile-of-poo',
    combo: '💀💩',
    emojis: ['skull', 'pile-of-poo'],
    name: 'Dead Poop',
    category: 'humor',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 76,
    tags: ['crude', 'dead', 'gross'],
  },
  {
    slug: 'partying-face-confetti',
    combo: '🥳🎊',
    emojis: ['partying-face', 'confetti-ball'],
    name: 'Party Confetti',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 86,
    tags: ['celebrate', 'joy', 'win'],
  },
  {
    slug: 'tears-of-joy-fire',
    combo: '🤣🔥',
    emojis: ['face-with-tears-of-joy', 'fire'],
    name: 'Laughing Fire',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 85,
    tags: ['laugh', 'fire', 'hype'],
  },
  {
    slug: 'nerd-glasses-cool',
    combo: '🤓😎',
    emojis: ['nerd-face', 'smiling-face-with-sunglasses'],
    name: 'Nerd Cool',
    category: 'humor',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 78,
    tags: ['geek', 'cool', 'duo'],
  },
  {
    slug: 'holding-back-tears-pleading',
    combo: '🥹🥺',
    emojis: ['holding-back-tears', 'pleading'],
    name: 'Holding Tears Pleading',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 82,
    tags: ['tender', 'soft', 'ask'],
  },
  {
    slug: 'melting-face-fire',
    combo: '🫠🔥',
    emojis: ['melting-face', 'fire'],
    name: 'Melting Heat',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 80,
    tags: ['heat', 'soft', 'melt'],
  },
  {
    slug: 'smiling-devil-fire',
    combo: '😈🔥',
    emojis: ['smiling-devil', 'fire'],
    name: 'Devilish Fire',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 81,
    tags: ['mischief', 'evil', 'playful'],
  },
  {
    slug: 'grimacing-sweat',
    combo: '😬💦',
    emojis: ['grimacing-face', 'sweat-droplets'],
    name: 'Awkward Sweat',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 80,
    tags: ['awkward', 'tense', 'oops'],
  },
  {
    slug: 'angry-face-anger-symbol',
    combo: '😠💢',
    name: 'Angry Anger',
    emojis: ['angry-face', 'anger-symbol'],
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 78,
    tags: ['mad', 'frustrated', 'symbol'],
  },
  {
    slug: 'pensive-cloud',
    combo: '😔☁️',
    emojis: ['pensive', 'cloud'],
    name: 'Pensive Cloud',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 76,
    tags: ['sad', 'blue', 'thoughtful'],
  },
  {
    slug: 'smiling-halo-sparkles',
    combo: '😇✨',
    emojis: ['smiling-with-halo', 'sparkles'],
    name: 'Angel Sparkle',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 79,
    tags: ['angel', 'innocent', 'glow'],
  },
  {
    slug: 'relieved-face-sweat-drop',
    combo: '😌💧',
    emojis: ['relieved-face', 'droplet'],
    name: 'Relieved Drop',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 77,
    tags: ['relief', 'breathe', 'whew'],
  },
  {
    slug: 'fearful-scream',
    combo: '😨😱',
    emojis: ['fearful-face', 'face-screaming-in-fear'],
    name: 'Fearful Scream',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 79,
    tags: ['scared', 'shock', 'horror'],
  },
  {
    slug: 'dizzy-face-stars',
    combo: '😵‍💫⭐',
    emojis: ['dizzy-face', 'star'],
    name: 'Dizzy Star',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 75,
    tags: ['dizzy', 'overwhelmed', 'spinning'],
  },
  {
    slug: 'cold-face-snowflake',
    combo: '🥶❄️',
    emojis: ['cold-face', 'snowflake'],
    name: 'Cold Snowflake',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 78,
    tags: ['cold', 'freeze', 'winter'],
  },
  {
    slug: 'hot-face-fire',
    combo: '🥵🔥',
    emojis: ['hot-face', 'fire'],
    name: 'Hot Fire',
    category: 'reaction',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 81,
    tags: ['heat', 'sweat', 'flirty'],
  },
  {
    slug: 'flushed-face-shy-blush',
    combo: '😳☺️',
    emojis: ['flushed-face', 'smiling-face'],
    name: 'Flushed Shy',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 77,
    tags: ['shy', 'blush', 'cute'],
  },
  {
    slug: 'upside-down-wink',
    combo: '🙃😉',
    emojis: ['upside-down-face', 'winking-face'],
    name: 'Upside Wink',
    category: 'humor',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 76,
    tags: ['silly', 'flirty', 'wink'],
  },
  {
    slug: 'sleepy-zzz',
    combo: '😪💤',
    emojis: ['sleepy-face', 'zzz'],
    name: 'Sleepy Zzz',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 79,
    tags: ['sleep', 'tired', 'zzz'],
  },
  {
    slug: 'sleeping-face-night-sky',
    combo: '😴🌃',
    emojis: ['sleeping-face', 'night-sky'],
    name: 'Sleepy Night',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 1,
    popularity: 75,
    tags: ['sleep', 'night', 'rest'],
  },
  {
    slug: 'crying-face-rain-cloud',
    combo: '😢🌧️',
    emojis: ['crying-face', 'cloud-with-rain'],
    name: 'Crying Rain',
    category: 'emotion',
    family: 'smileys-emotion',
    variant: 2,
    popularity: 80,
    tags: ['sad', 'rain', 'tear'],
  },
  {
    slug: 'monocle-thinking',
    combo: '🧐🤔',
    emojis: ['face-with-monocle', 'thinking-face'],
    name: 'Monocle Think',
    category: 'humor',
    family: 'smileys-emotion',
    variant: 0,
    popularity: 74,
    tags: ['inspect', 'think', 'old-school'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 3: Hand Gestures & Body Language — 25 combos
  //   reaction 13 / humor 7 / sarcasm 5
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'thumbs-up-check-mark',
    combo: '👍✅',
    emojis: ['thumbs-up', 'check-mark-button'],
    name: 'Thumbs Up Check',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 86,
    tags: ['approve', 'good', 'confirm'],
  },
  {
    slug: 'thumbs-down-no-entry',
    combo: '👎🚫',
    emojis: ['thumbs-down', 'no-entry'],
    name: 'Thumbs Down No',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 81,
    tags: ['reject', 'no', 'block'],
  },
  {
    slug: 'folded-hands-thank-you',
    combo: '🙏💖',
    emojis: ['folded-hands', 'sparkling-heart'],
    name: 'Praying Heart',
    category: 'reaction',
    family: 'hands-body',
    variant: 2,
    popularity: 84,
    tags: ['thanks', 'grateful', 'warm'],
  },
  {
    slug: 'clapping-sparkles',
    combo: '👏✨',
    emojis: ['clapping-hands', 'sparkles'],
    name: 'Clapping Sparkle',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 85,
    tags: ['applaud', 'celebrate', 'glow'],
  },
  {
    slug: 'waving-hand-hello',
    combo: '👋👋',
    emojis: ['waving-hand', 'waving-hand'],
    name: 'Double Wave',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 80,
    tags: ['hello', 'wave', 'greet'],
  },
  {
    slug: 'flexed-biceps-100',
    combo: '💪💯',
    emojis: ['flexed-biceps', 'hundred-points'],
    name: 'Strong 100',
    category: 'reaction',
    family: 'hands-body',
    variant: 2,
    popularity: 87,
    tags: ['strong', 'perfect', 'flex'],
  },
  {
    slug: 'ok-hand-check-mark',
    combo: '👌✅',
    emojis: ['ok-hand', 'check-mark-button'],
    name: 'Ok Confirm',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 82,
    tags: ['ok', 'confirm', 'good'],
  },
  {
    slug: 'pointing-right-arrow',
    combo: '👉➡️',
    emojis: ['backhand-index-pointing-right', 'right-arrow'],
    name: 'Point Right',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 79,
    tags: ['this', 'look', 'right'],
  },
  {
    slug: 'pointing-down-no',
    combo: '👇🚫',
    emojis: ['backhand-index-down', 'no-entry'],
    name: 'Point Down No',
    category: 'sarcasm',
    family: 'hands-body',
    variant: 2,
    popularity: 75,
    tags: ['not-this', 'reject', 'below'],
  },
  {
    slug: 'victory-hand-sparkles',
    combo: '✌️✨',
    emojis: ['victory-hand', 'sparkles'],
    name: 'Peace Sparkle',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 81,
    tags: ['peace', 'win', 'glow'],
  },
  {
    slug: 'raised-hand-stop',
    combo: '✋🛑',
    emojis: ['raised-hand', 'stop-sign'],
    name: 'Raised Hand Stop',
    category: 'sarcasm',
    family: 'hands-body',
    variant: 1,
    popularity: 78,
    tags: ['stop', 'halt', 'pause'],
  },
  {
    slug: 'facepalm-table-flip',
    combo: '🤦🙃',
    emojis: ['facepalm', 'upside-down-face'],
    name: 'Facepalm Flip',
    category: 'humor',
    family: 'hands-body',
    variant: 2,
    popularity: 77,
    tags: ['oops', 'flop', 'disaster'],
  },
  {
    slug: 'shrug-tipping-hand',
    combo: '🤷💁',
    emojis: ['shrug', 'person-tipping-hand'],
    name: 'Shrug Whatever',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 79,
    tags: ['idk', 'whatever', 'meh'],
  },
  {
    slug: 'call-me-hand-phone',
    combo: '🤙📱',
    emojis: ['call-me-hand', 'mobile-phone'],
    name: 'Call Me Phone',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 78,
    tags: ['call', 'phone', 'hang-loose'],
  },
  {
    slug: 'crossed-fingers-clover',
    combo: '🤞🍀',
    emojis: ['crossed-fingers', 'four-leaf-clover'],
    name: 'Cross Fingers Luck',
    category: 'reaction',
    family: 'hands-body',
    variant: 2,
    popularity: 82,
    tags: ['luck', 'hope', 'wish'],
  },
  {
    slug: 'muscle-fire-flex',
    combo: '💪🔥',
    emojis: ['flexed-biceps', 'fire'],
    name: 'Muscle Fire',
    category: 'humor',
    family: 'hands-body',
    variant: 0,
    popularity: 84,
    tags: ['flex', 'fire', 'strong'],
  },
  {
    slug: 'nail-polish-sparkle-heart',
    combo: '💅💖',
    emojis: ['nail-polish', 'sparkling-heart'],
    name: 'Nail Polish Heart',
    category: 'humor',
    family: 'hands-body',
    variant: 1,
    popularity: 79,
    tags: ['nails', 'self-care', 'flair'],
  },
  {
    slug: 'raised-fist-fire',
    combo: '✊🔥',
    emojis: ['raised-fist', 'fire'],
    name: 'Fist Fire',
    category: 'reaction',
    family: 'hands-body',
    variant: 2,
    popularity: 81,
    tags: ['power', 'fire', 'fight'],
  },
  {
    slug: 'palms-up-together-please',
    combo: '🤲🥺',
    emojis: ['palms-up-together', 'pleading'],
    name: 'Palms Up Please',
    category: 'humor',
    family: 'hands-body',
    variant: 0,
    popularity: 76,
    tags: ['please', 'beg', 'soft'],
  },
  {
    slug: 'open-hands-hug',
    combo: '👐🤗',
    emojis: ['open-hands', 'hugging-face'],
    name: 'Open Arms Hug',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 80,
    tags: ['hug', 'open', 'welcome'],
  },
  {
    slug: 'middle-finger-anger',
    combo: '🖕💢',
    emojis: ['middle-finger', 'anger-symbol'],
    name: 'Middle Finger Anger',
    category: 'sarcasm',
    family: 'hands-body',
    variant: 2,
    popularity: 73,
    tags: ['flip-off', 'anger', 'rude'],
  },
  {
    slug: 'hand-heart-kiss-mark',
    combo: '🫶💋',
    emojis: ['hand-heart', 'kiss-mark'],
    name: 'Hand Heart Kiss',
    category: 'reaction',
    family: 'hands-body',
    variant: 0,
    popularity: 83,
    tags: ['heart-hands', 'kiss', 'love'],
  },
  {
    slug: 'point-up-lightbulb',
    combo: '☝️💡',
    emojis: ['index-pointing-up', 'light-bulb'],
    name: 'Point Idea',
    category: 'reaction',
    family: 'hands-body',
    variant: 1,
    popularity: 80,
    tags: ['idea', 'eureka', 'point'],
  },
  {
    slug: 'thumbs-up-clap',
    combo: '👍👏',
    emojis: ['thumbs-up', 'clapping-hands'],
    name: 'Thumbs Clap',
    category: 'reaction',
    family: 'hands-body',
    variant: 2,
    popularity: 81,
    tags: ['approve', 'clap', 'good-job'],
  },
  {
    slug: 'wink-pointing-finger',
    combo: '😉👉',
    emojis: ['winking-face', 'backhand-index-pointing-right'],
    name: 'Wink Point',
    category: 'sarcasm',
    family: 'hands-body',
    variant: 0,
    popularity: 75,
    tags: ['wink', 'point', 'flirty'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 4: Animals & Creatures — 25 combos
  //   humor 9 / reaction 8 / emotion 4 / other 4
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'cat-face-heart-eyes',
    combo: '🐱😍',
    emojis: ['cat-face', 'smiling-face-with-heart-eyes'],
    name: 'Cat Heart Eyes',
    category: 'reaction',
    family: 'animals',
    variant: 0,
    popularity: 84,
    tags: ['cat', 'love', 'cute'],
  },
  {
    slug: 'dog-face-tongue',
    combo: '🐶👅',
    emojis: ['dog-face', 'tongue'],
    name: 'Dog Tongue',
    category: 'humor',
    family: 'animals',
    variant: 1,
    popularity: 78,
    tags: ['dog', 'lick', 'puppy'],
  },
  {
    slug: 'unicorn-sparkles',
    combo: '🦄✨',
    emojis: ['unicorn-face', 'sparkles'],
    name: 'Unicorn Sparkle',
    category: 'reaction',
    family: 'animals',
    variant: 2,
    popularity: 82,
    tags: ['magic', 'sparkle', 'fantasy'],
  },
  {
    slug: 'fox-face-cool',
    combo: '🦊😎',
    emojis: ['fox-face', 'smiling-face-with-sunglasses'],
    name: 'Fox Cool',
    category: 'humor',
    family: 'animals',
    variant: 0,
    popularity: 79,
    tags: ['fox', 'cool', 'sly'],
  },
  {
    slug: 'panda-bamboo',
    combo: '🐼🎋',
    emojis: ['panda-face', 'bamboo'],
    name: 'Panda Bamboo',
    category: 'other',
    family: 'animals',
    variant: 1,
    popularity: 76,
    tags: ['panda', 'bamboo', 'cute'],
  },
  {
    slug: 'penguin-cold',
    combo: '🐧🥶',
    emojis: ['penguin', 'cold-face'],
    name: 'Penguin Cold',
    category: 'humor',
    family: 'animals',
    variant: 2,
    popularity: 80,
    tags: ['penguin', 'cold', 'icy'],
  },
  {
    slug: 'butterfly-flower',
    combo: '🦋🌸',
    emojis: ['butterfly', 'cherry-blossom'],
    name: 'Butterfly Blossom',
    category: 'emotion',
    family: 'animals',
    variant: 0,
    popularity: 81,
    tags: ['spring', 'soft', 'flutter'],
  },
  {
    slug: 'bee-flower',
    combo: '🐝🌻',
    emojis: ['bee', 'sunflower'],
    name: 'Bee Sunflower',
    category: 'other',
    family: 'animals',
    variant: 1,
    popularity: 80,
    tags: ['bee', 'sunflower', 'pollinate'],
  },
  {
    slug: 'snail-slow-turtle',
    combo: '🐌🐢',
    emojis: ['snail', 'turtle'],
    name: 'Snail Turtle',
    category: 'humor',
    family: 'animals',
    variant: 2,
    popularity: 73,
    tags: ['slow', 'pair', 'chill'],
  },
  {
    slug: 'octopus-sparkles',
    combo: '🐙✨',
    emojis: ['octopus', 'sparkles'],
    name: 'Octopus Sparkle',
    category: 'reaction',
    family: 'animals',
    variant: 0,
    popularity: 75,
    tags: ['octopus', 'magic', 'tentacle'],
  },
  {
    slug: 'dolphin-wave',
    combo: '🐬🌊',
    emojis: ['dolphin', 'water-wave'],
    name: 'Dolphin Wave',
    category: 'emotion',
    family: 'animals',
    variant: 1,
    popularity: 78,
    tags: ['dolphin', 'wave', 'ocean'],
  },
  {
    slug: 'whale-spouting',
    combo: '🐳💦',
    emojis: ['whale', 'sweat-droplets'],
    name: 'Whale Spout',
    category: 'humor',
    family: 'animals',
    variant: 2,
    popularity: 76,
    tags: ['whale', 'spout', 'ocean'],
  },
  {
    slug: 'shark-money',
    combo: '🦈💰',
    emojis: ['shark', 'money-bag'],
    name: 'Shark Money',
    category: 'reaction',
    family: 'animals',
    variant: 0,
    popularity: 74,
    tags: ['shark', 'money', 'predator'],
  },
  {
    slug: 'frog-face-laughing',
    combo: '🐸🤣',
    emojis: ['frog-face', 'face-with-tears-of-joy'],
    name: 'Frog Laugh',
    category: 'humor',
    family: 'animals',
    variant: 1,
    popularity: 79,
    tags: ['frog', 'laugh', 'meme'],
  },
  {
    slug: 'koala-sleepy',
    combo: '🐨😴',
    emojis: ['koala', 'sleeping-face'],
    name: 'Koala Sleepy',
    category: 'emotion',
    family: 'animals',
    variant: 2,
    popularity: 77,
    tags: ['koala', 'sleep', 'cute'],
  },
  {
    slug: 'lion-face-crown',
    combo: '🦁👑',
    emojis: ['lion-face', 'crown'],
    name: 'Lion Crown',
    category: 'reaction',
    family: 'animals',
    variant: 0,
    popularity: 80,
    tags: ['king', 'lion', 'royal'],
  },
  {
    slug: 'tiger-face-fire',
    combo: '🐯🔥',
    emojis: ['tiger-face', 'fire'],
    name: 'Tiger Fire',
    category: 'reaction',
    family: 'animals',
    variant: 1,
    popularity: 78,
    tags: ['tiger', 'fire', 'wild'],
  },
  {
    slug: 'chicken-egg',
    combo: '🐔🥚',
    emojis: ['chicken', 'egg'],
    name: 'Chicken Egg',
    category: 'other',
    family: 'animals',
    variant: 2,
    popularity: 75,
    tags: ['chicken', 'egg', 'poultry'],
  },
  {
    slug: 'rabbit-carrot',
    combo: '🐰🥕',
    emojis: ['rabbit-face', 'carrot'],
    name: 'Rabbit Carrot',
    category: 'other',
    family: 'animals',
    variant: 0,
    popularity: 76,
    tags: ['rabbit', 'carrot', 'snack'],
  },
  {
    slug: 'owl-night-sky',
    combo: '🦉🌃',
    emojis: ['owl', 'night-sky'],
    name: 'Owl Night',
    category: 'humor',
    family: 'animals',
    variant: 1,
    popularity: 77,
    tags: ['owl', 'night', 'wise'],
  },
  {
    slug: 'duck-water',
    combo: '🦆💧',
    emojis: ['duck', 'droplet'],
    name: 'Duck Drop',
    category: 'humor',
    family: 'animals',
    variant: 2,
    popularity: 74,
    tags: ['duck', 'water', 'pond'],
  },
  {
    slug: 'spiral-shell-wave',
    combo: '🐚🌊',
    emojis: ['spiral-shell', 'water-wave'],
    name: 'Shell Wave',
    category: 'emotion',
    family: 'animals',
    variant: 0,
    popularity: 75,
    tags: ['shell', 'ocean', 'calm'],
  },
  {
    slug: 'dragon-fire',
    combo: '🐉🔥',
    emojis: ['dragon', 'fire'],
    name: 'Dragon Fire',
    category: 'reaction',
    family: 'animals',
    variant: 1,
    popularity: 81,
    tags: ['dragon', 'fire', 'myth'],
  },
  {
    slug: 'bat-night',
    combo: '🦇🌙',
    emojis: ['bat', 'crescent-moon'],
    name: 'Bat Moon',
    category: 'humor',
    family: 'animals',
    variant: 2,
    popularity: 75,
    tags: ['bat', 'night', 'spooky'],
  },
  {
    slug: 'wolf-moon',
    combo: '🐺🌕',
    emojis: ['wolf-face', 'full-moon'],
    name: 'Wolf Moon',
    category: 'reaction',
    family: 'animals',
    variant: 0,
    popularity: 78,
    tags: ['wolf', 'moon', 'wild'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 5: Food & Drink — 25 combos
  //   food 18 / celebration 4 / flirting 3
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'pizza-beer',
    combo: '🍕🍺',
    emojis: ['pizza', 'beer-mug'],
    name: 'Pizza Beer',
    category: 'food',
    family: 'food-drink',
    variant: 0,
    popularity: 86,
    tags: ['pizza', 'beer', 'night'],
  },
  {
    slug: 'coffee-morning-sun',
    combo: '☀️☕',
    emojis: ['sun', 'hot-beverage'],
    name: 'Coffee Morning Sun',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 87,
    tags: ['coffee', 'morning', 'sun'],
  },
  {
    slug: 'birthday-cake-candle',
    combo: '🎂🕯️',
    emojis: ['birthday-cake', 'candle'],
    name: 'Birthday Candle',
    category: 'celebration',
    family: 'food-drink',
    variant: 2,
    popularity: 84,
    tags: ['birthday', 'wish', 'cake'],
  },
  {
    slug: 'wine-cheese',
    combo: '🍷🧀',
    emojis: ['wine-glass', 'cheese-wedge-emoji'],
    name: 'Wine Cheese',
    category: 'food',
    family: 'food-drink',
    variant: 0,
    popularity: 81,
    tags: ['wine', 'cheese', 'charcuterie'],
  },
  {
    slug: 'donut-coffee-cup',
    combo: '🍩☕',
    emojis: ['doughnut', 'hot-beverage'],
    name: 'Donut Coffee',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 80,
    tags: ['donut', 'coffee', 'morning'],
  },
  {
    slug: 'sushi-sparkles',
    combo: '🍣✨',
    emojis: ['sushi', 'sparkles'],
    name: 'Sushi Sparkles',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 79,
    tags: ['sushi', 'sparkle', 'fresh'],
  },
  {
    slug: 'taco-spicy',
    combo: '🌮🌶',
    emojis: ['taco', 'hot-pepper'],
    name: 'Taco Spicy',
    category: 'food',
    family: 'food-drink',
    variant: 0,
    popularity: 82,
    tags: ['taco', 'spicy', 'hot'],
  },
  {
    slug: 'ice-cream-summer',
    combo: '🍦☀️',
    emojis: ['ice-cream', 'sun'],
    name: 'Ice Cream Sun',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 80,
    tags: ['ice-cream', 'summer', 'sun'],
  },
  {
    slug: 'fries-burger',
    combo: '🍟🍔',
    emojis: ['fries', 'hamburger'],
    name: 'Burger Fries',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 83,
    tags: ['fries', 'burger', 'combo'],
  },
  {
    slug: 'apple-fruit-bowl',
    combo: '🍎🍇',
    emojis: ['red-apple', 'grapes'],
    name: 'Apple Grapes',
    category: 'food',
    family: 'food-drink',
    variant: 0,
    popularity: 76,
    tags: ['fruit', 'snack', 'healthy'],
  },
  {
    slug: 'croissant-coffee',
    combo: '🥐☕',
    emojis: ['croissant', 'hot-beverage'],
    name: 'Croissant Coffee',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 82,
    tags: ['croissant', 'breakfast', 'paris'],
  },
  {
    slug: 'bento-sparkles',
    combo: '🍱✨',
    emojis: ['bento', 'sparkles'],
    name: 'Bento Sparkle',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 76,
    tags: ['bento', 'lunch', 'cute'],
  },
  {
    slug: 'spaghetti-heart',
    combo: '🍝❤️',
    emojis: ['spaghetti', 'red-heart'],
    name: 'Spaghetti Love',
    category: 'flirting',
    family: 'food-drink',
    variant: 0,
    popularity: 78,
    tags: ['spaghetti', 'love', 'date'],
  },
  {
    slug: 'ramen-fire',
    combo: '🍜🔥',
    emojis: ['ramen', 'fire'],
    name: 'Spicy Ramen',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 80,
    tags: ['ramen', 'spicy', 'hot'],
  },
  {
    slug: 'hot-dog-100',
    combo: '🌭💯',
    emojis: ['hot-dog', 'hundred-points'],
    name: 'Hot Dog 100',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 74,
    tags: ['hot-dog', 'perfect', 'snack'],
  },
  {
    slug: 'pancakes-maple',
    combo: '🥞🍁',
    emojis: ['pancakes', 'maple-leaf'],
    name: 'Pancakes Maple',
    category: 'food',
    family: 'food-drink',
    variant: 0,
    popularity: 77,
    tags: ['pancakes', 'maple', 'breakfast'],
  },
  {
    slug: 'cookie-milk',
    combo: '🍪🥛',
    emojis: ['cookie', 'glass-of-milk'],
    name: 'Cookie Milk',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 82,
    tags: ['cookie', 'milk', 'classic'],
  },
  {
    slug: 'popcorn-movie',
    combo: '🍿🎬',
    emojis: ['popcorn', 'clapper-board'],
    name: 'Popcorn Movie',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 81,
    tags: ['movie', 'snack', 'night'],
  },
  {
    slug: 'cake-sparkles-party',
    combo: '🎂✨🎉',
    emojis: ['birthday-cake', 'sparkles', 'party-popper'],
    name: 'Cake Sparkle Party',
    category: 'celebration',
    family: 'food-drink',
    variant: 0,
    popularity: 83,
    tags: ['birthday', 'party', 'cake'],
  },
  {
    slug: 'lollipop-kid',
    combo: '🍭🧒',
    emojis: ['lollipop', 'child'],
    name: 'Lollipop Kid',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 73,
    tags: ['candy', 'kid', 'sweet'],
  },
  {
    slug: 'watermelon-summer',
    combo: '🍉☀️',
    emojis: ['watermelon', 'sun'],
    name: 'Watermelon Summer',
    category: 'food',
    family: 'food-drink',
    variant: 2,
    popularity: 79,
    tags: ['summer', 'fruit', 'fresh'],
  },
  {
    slug: 'candy-heart-eyes',
    combo: '🍬😍',
    emojis: ['candy', 'smiling-face-with-heart-eyes'],
    name: 'Candy Heart Eyes',
    category: 'flirting',
    family: 'food-drink',
    variant: 0,
    popularity: 76,
    tags: ['sweet', 'love', 'treat'],
  },
  {
    slug: 'avocado-toast',
    combo: '🥑🍞',
    emojis: ['avocado', 'bread'],
    name: 'Avocado Toast',
    category: 'food',
    family: 'food-drink',
    variant: 1,
    popularity: 78,
    tags: ['avocado', 'toast', 'brunch'],
  },
  {
    slug: 'strawberry-chocolate',
    combo: '🍓🍫',
    emojis: ['strawberry', 'chocolate-bar'],
    name: 'Strawberry Chocolate',
    category: 'flirting',
    family: 'food-drink',
    variant: 2,
    popularity: 79,
    tags: ['strawberry', 'chocolate', 'romance'],
  },
  {
    slug: 'mango-sparkles',
    combo: '🥭✨',
    emojis: ['mango', 'sparkles'],
    name: 'Mango Sparkle',
    category: 'celebration',
    family: 'food-drink',
    variant: 0,
    popularity: 75,
    tags: ['mango', 'fresh', 'tropical'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 6: Travel, Places & Adventure — 25 combos
  //   travel 18 / celebration 4 / emotion 3
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'plane-suitcase-departure',
    combo: '✈️🧳🛫',
    emojis: ['airplane', 'luggage', 'airplane-departure'],
    name: 'Jet Set Departure',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 88,
    tags: ['plane', 'trip', 'depart'],
  },
  {
    slug: 'beach-sun-umbrella',
    combo: '🏖️☀️',
    emojis: ['beach-with-umbrella-emoji', 'sun'],
    name: 'Beach Sun',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 85,
    tags: ['beach', 'summer', 'vacation'],
  },
  {
    slug: 'mountain-sun',
    combo: '⛰️☀️',
    emojis: ['mountain', 'sun'],
    name: 'Mountain Sun',
    category: 'travel',
    family: 'travel-places',
    variant: 2,
    popularity: 80,
    tags: ['mountain', 'hike', 'sun'],
  },
  {
    slug: 'compass-paper-map',
    combo: '🧭🗺️',
    emojis: ['compass', 'world-map'],
    name: 'Compass Map',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 79,
    tags: ['map', 'compass', 'explore'],
  },
  {
    slug: 'passport-plane-arrival',
    combo: '🛂🛬',
    emojis: ['passport-control', 'airplane-arrival'],
    name: 'Passport Arrival',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 81,
    tags: ['arrival', 'border', 'fly'],
  },
  {
    slug: 'hotel-bed',
    combo: '🏨🛏️',
    emojis: ['hotel', 'bed'],
    name: 'Hotel Bed',
    category: 'travel',
    family: 'travel-places',
    variant: 2,
    popularity: 78,
    tags: ['hotel', 'sleep', 'trip'],
  },
  {
    slug: 'tent-campfire',
    combo: '⛺🔥',
    emojis: ['tent', 'fire'],
    name: 'Tent Fire',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 80,
    tags: ['camping', 'fire', 'tent'],
  },
  {
    slug: 'car-road-trip',
    combo: '🚗🛣️',
    emojis: ['automobile', 'motorway'],
    name: 'Road Trip',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 82,
    tags: ['road', 'drive', 'trip'],
  },
  {
    slug: 'train-station',
    combo: '🚆🚉',
    emojis: ['train', 'station'],
    name: 'Train Station',
    category: 'travel',
    family: 'travel-places',
    variant: 2,
    popularity: 77,
    tags: ['train', 'station', 'commute'],
  },
  {
    slug: 'bicycle-sun',
    combo: '🚲☀️',
    emojis: ['bicycle', 'sun'],
    name: 'Bicycle Sun',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 76,
    tags: ['bike', 'sun', 'ride'],
  },
  {
    slug: 'boat-wave',
    combo: '⛵🌊',
    emojis: ['sailboat', 'water-wave'],
    name: 'Sailboat Wave',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 79,
    tags: ['boat', 'wave', 'sail'],
  },
  {
    slug: 'rocket-fire-launch',
    combo: '🚀🔥',
    emojis: ['rocket', 'fire'],
    name: 'Rocket Launch',
    category: 'celebration',
    family: 'travel-places',
    variant: 2,
    popularity: 84,
    tags: ['rocket', 'launch', 'go'],
  },
  {
    slug: 'anchor-ocean',
    combo: '⚓🌊',
    emojis: ['anchor', 'water-wave'],
    name: 'Anchor Ocean',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 77,
    tags: ['anchor', 'sea', 'dock'],
  },
  {
    slug: 'helicopter-fly',
    combo: '🚁☁️',
    emojis: ['helicopter', 'cloud'],
    name: 'Helicopter Sky',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 76,
    tags: ['heli', 'sky', 'fly'],
  },
  {
    slug: 'snow-mountain-ski',
    combo: '🏔️⛷️',
    emojis: ['snow-capped-mountain', 'skier'],
    name: 'Snow Mountain Ski',
    category: 'travel',
    family: 'travel-places',
    variant: 2,
    popularity: 78,
    tags: ['snow', 'ski', 'mountain'],
  },
  {
    slug: 'desert-cactus',
    combo: '🏜️🌵',
    emojis: ['desert', 'cactus'],
    name: 'Desert Cactus',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 75,
    tags: ['desert', 'cactus', 'arid'],
  },
  {
    slug: 'tropical-island-palm',
    combo: '🏝️🌴',
    emojis: ['desert-island', 'palm-tree'],
    name: 'Tropical Island',
    category: 'travel',
    family: 'travel-places',
    variant: 1,
    popularity: 81,
    tags: ['island', 'tropical', 'palm'],
  },
  {
    slug: 'cityscape-night-sky',
    combo: '🏙️🌃',
    emojis: ['cityscape', 'night-sky'],
    name: 'Cityscape Night',
    category: 'emotion',
    family: 'travel-places',
    variant: 2,
    popularity: 80,
    tags: ['city', 'night', 'skyline'],
  },
  {
    slug: 'sunrise-coffee',
    combo: '🌅☕',
    emojis: ['sunrise', 'hot-beverage'],
    name: 'Sunrise Coffee',
    category: 'emotion',
    family: 'travel-places',
    variant: 0,
    popularity: 82,
    tags: ['sunrise', 'morning', 'coffee'],
  },
  {
    slug: 'sunset-heart',
    combo: '🌇❤️',
    emojis: ['sunset', 'red-heart'],
    name: 'Sunset Love',
    category: 'emotion',
    family: 'travel-places',
    variant: 1,
    popularity: 81,
    tags: ['sunset', 'love', 'romantic'],
  },
  {
    slug: 'fountain-wish',
    combo: '⛲🌟',
    emojis: ['fountain', 'glowing-star'],
    name: 'Fountain Wish',
    category: 'celebration',
    family: 'travel-places',
    variant: 2,
    popularity: 76,
    tags: ['fountain', 'wish', 'magic'],
  },
  {
    slug: 'national-park-hike',
    combo: '🏞️🥾',
    emojis: ['national-park', 'hiking-boot'],
    name: 'National Park Hike',
    category: 'travel',
    family: 'travel-places',
    variant: 0,
    popularity: 78,
    tags: ['park', 'hike', 'nature'],
  },
  {
    slug: 'volcano-fire',
    combo: '🌋🔥',
    emojis: ['volcano', 'fire'],
    name: 'Volcano Fire',
    category: 'celebration',
    family: 'travel-places',
    variant: 1,
    popularity: 75,
    tags: ['volcano', 'fire', 'erupt'],
  },
  {
    slug: 'tram-city',
    combo: '🚊🏙️',
    emojis: ['tram', 'cityscape'],
    name: 'Tram City',
    category: 'travel',
    family: 'travel-places',
    variant: 2,
    popularity: 73,
    tags: ['tram', 'city', 'commute'],
  },
  {
    slug: 'globe-with-meridians-plane',
    combo: '🌐✈️',
    emojis: ['globe-with-meridians', 'airplane'],
    name: 'Globe Plane',
    category: 'celebration',
    family: 'travel-places',
    variant: 0,
    popularity: 80,
    tags: ['world', 'travel', 'globe'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 7: Sports, Music & Activities — 25 combos
  //   celebration 10 / humor 8 / emotion 4 / reaction 3
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'trophy-100',
    combo: '🏆💯',
    emojis: ['trophy', 'hundred-points'],
    name: 'Trophy Real',
    category: 'celebration',
    family: 'sports-music',
    variant: 0,
    popularity: 86,
    tags: ['win', 'trophy', 'real'],
  },
  {
    slug: 'medal-star',
    combo: '🏅⭐',
    emojis: ['medal', 'star'],
    name: 'Medal Star',
    category: 'celebration',
    family: 'sports-music',
    variant: 1,
    popularity: 80,
    tags: ['medal', 'star', 'win'],
  },
  {
    slug: 'first-place-medal-sparkles',
    combo: '🥇✨',
    emojis: ['first-place-medal', 'sparkles'],
    name: 'Gold Sparkle',
    category: 'celebration',
    family: 'sports-music',
    variant: 2,
    popularity: 84,
    tags: ['gold', 'sparkle', 'first'],
  },
  {
    slug: 'soccer-ball-goal',
    combo: '⚽🥅',
    emojis: ['soccer-ball', 'goal-net'],
    name: 'Soccer Goal',
    category: 'celebration',
    family: 'sports-music',
    variant: 0,
    popularity: 81,
    tags: ['soccer', 'goal', 'score'],
  },
  {
    slug: 'basketball-hoop',
    combo: '🏀⛹️',
    emojis: ['basketball', 'basketball-player'],
    name: 'Basketball Play',
    category: 'celebration',
    family: 'sports-music',
    variant: 1,
    popularity: 78,
    tags: ['basket', 'sport', 'play'],
  },
  {
    slug: 'guitar-music-notes',
    combo: '🎸🎶',
    emojis: ['guitar', 'musical-notes'],
    name: 'Guitar Music',
    category: 'reaction',
    family: 'sports-music',
    variant: 2,
    popularity: 82,
    tags: ['guitar', 'music', 'tune'],
  },
  {
    slug: 'headphone-music-note',
    combo: '🎧🎵',
    emojis: ['headphone', 'musical-note'],
    name: 'Headphone Tune',
    category: 'reaction',
    family: 'sports-music',
    variant: 0,
    popularity: 80,
    tags: ['music', 'listen', 'vibe'],
  },
  {
    slug: 'microphone-star',
    combo: '🎤⭐',
    emojis: ['microphone', 'star'],
    name: 'Mic Star',
    category: 'celebration',
    family: 'sports-music',
    variant: 1,
    popularity: 78,
    tags: ['mic', 'star', 'sing'],
  },
  {
    slug: 'video-game-dart',
    combo: '🎮🎯',
    emojis: ['video-game', 'bullseye'],
    name: 'Game Dart',
    category: 'humor',
    family: 'sports-music',
    variant: 2,
    popularity: 80,
    tags: ['game', 'play', 'dart'],
  },
  {
    slug: 'game-die-lucky',
    combo: '🎲🍀',
    emojis: ['game-die', 'four-leaf-clover'],
    name: 'Dice Lucky',
    category: 'humor',
    family: 'sports-music',
    variant: 0,
    popularity: 76,
    tags: ['dice', 'luck', 'game'],
  },
  {
    slug: '8-ball-magic',
    combo: '🎱✨',
    emojis: ['8-ball', 'sparkles'],
    name: 'Magic 8-Ball',
    category: 'reaction',
    family: 'sports-music',
    variant: 1,
    popularity: 77,
    tags: ['magic', 'pool', 'mystery'],
  },
  {
    slug: 'musical-keyboard-music-notes',
    combo: '🎹🎶',
    emojis: ['musical-keyboard', 'musical-notes'],
    name: 'Keyboard Music',
    category: 'reaction',
    family: 'sports-music',
    variant: 2,
    popularity: 76,
    tags: ['keyboard', 'music', 'play'],
  },
  {
    slug: 'drum-fire',
    combo: '🥁🔥',
    emojis: ['drum', 'fire'],
    name: 'Drum Fire',
    category: 'celebration',
    family: 'sports-music',
    variant: 0,
    popularity: 78,
    tags: ['drum', 'fire', 'beat'],
  },
  {
    slug: 'artist-palette-sparkles',
    combo: '🎨✨',
    emojis: ['artist-palette', 'sparkles'],
    name: 'Palette Sparkle',
    category: 'celebration',
    family: 'sports-music',
    variant: 1,
    popularity: 77,
    tags: ['art', 'palette', 'create'],
  },
  {
    slug: 'performing-arts-mask',
    combo: '🎭🎟️',
    emojis: ['performing-arts', 'admission-tickets'],
    name: 'Theater Tickets',
    category: 'celebration',
    family: 'sports-music',
    variant: 2,
    popularity: 75,
    tags: ['theater', 'tickets', 'show'],
  },
  {
    slug: 'clapper-board-sparkles',
    combo: '🎬✨',
    emojis: ['clapper-board', 'sparkles'],
    name: 'Action Sparkle',
    category: 'celebration',
    family: 'sports-music',
    variant: 0,
    popularity: 78,
    tags: ['movie', 'action', 'sparkle'],
  },
  {
    slug: 'circus-tent-clown',
    combo: '🎪🤡',
    emojis: ['circus-tent', 'clown-face'],
    name: 'Circus Clown',
    category: 'humor',
    family: 'sports-music',
    variant: 1,
    popularity: 76,
    tags: ['circus', 'clown', 'show'],
  },
  {
    slug: 'boxing-glove-muscle',
    combo: '🥊💪',
    emojis: ['boxing-glove', 'flexed-biceps'],
    name: 'Boxing Muscle',
    category: 'humor',
    family: 'sports-music',
    variant: 2,
    popularity: 76,
    tags: ['box', 'fight', 'strong'],
  },
  {
    slug: 'martial-arts-kick',
    combo: '🥋🦵',
    emojis: ['martial-arts', 'leg'],
    name: 'Martial Arts Kick',
    category: 'humor',
    family: 'sports-music',
    variant: 0,
    popularity: 74,
    tags: ['martial', 'kick', 'art'],
  },
  {
    slug: 'skateboard-fire',
    combo: '🛹🔥',
    emojis: ['skateboard', 'fire'],
    name: 'Skate Fire',
    category: 'humor',
    family: 'sports-music',
    variant: 1,
    popularity: 76,
    tags: ['skate', 'fire', 'trick'],
  },
  {
    slug: 'snowboarder-mountain',
    combo: '🏂🏔️',
    emojis: ['snowboarder', 'snow-capped-mountain'],
    name: 'Snowboard Mountain',
    category: 'reaction',
    family: 'sports-music',
    variant: 2,
    popularity: 77,
    tags: ['snowboard', 'mountain', 'sport'],
  },
  {
    slug: 'fishing-pole-fish',
    combo: '🎣🐟',
    emojis: ['fishing-pole', 'fish'],
    name: 'Fishing Catch',
    category: 'humor',
    family: 'sports-music',
    variant: 0,
    popularity: 75,
    tags: ['fish', 'catch', 'calm'],
  },
  {
    slug: 'volleyball-ball',
    combo: '🏐🌊',
    emojis: ['volleyball', 'water-wave'],
    name: 'Beach Volleyball',
    category: 'reaction',
    family: 'sports-music',
    variant: 1,
    popularity: 76,
    tags: ['volley', 'beach', 'sport'],
  },
  {
    slug: 'tennis-ball-racket',
    combo: '🎾🏸',
    emojis: ['tennis', 'badminton'],
    name: 'Tennis Racket',
    category: 'humor',
    family: 'sports-music',
    variant: 2,
    popularity: 73,
    tags: ['tennis', 'racket', 'sport'],
  },
  {
    slug: 'rosette-sparkles',
    combo: '🎖️✨',
    emojis: ['rosette', 'sparkles'],
    name: 'Rosette Sparkle',
    category: 'emotion',
    family: 'sports-music',
    variant: 0,
    popularity: 75,
    tags: ['rosette', 'sparkle', 'award'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 8: Weather, Nature & Seasons — 25 combos
  //   emotion 9 / sarcasm 7 / humor 5 / other 4
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'rainbow-cloud-happy',
    combo: '🌈☁️',
    emojis: ['rainbow', 'cloud'],
    name: 'Rainbow Cloud',
    category: 'emotion',
    family: 'weather-nature',
    variant: 0,
    popularity: 81,
    tags: ['rainbow', 'cloud', 'soft'],
  },
  {
    slug: 'sun-cloud-breeze',
    combo: '☀️☁️',
    emojis: ['sun', 'cloud'],
    name: 'Sun Cloud',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 79,
    tags: ['sun', 'cloud', 'mild'],
  },
  {
    slug: 'snowflake-cold-snowman',
    combo: '❄️⛄',
    emojis: ['snowflake', 'snowman'],
    name: 'Snow Snowman',
    category: 'emotion',
    family: 'weather-nature',
    variant: 2,
    popularity: 82,
    tags: ['snow', 'snowman', 'winter'],
  },
  {
    slug: 'fire-flame-warm',
    combo: '🔥🔥',
    emojis: ['fire', 'fire'],
    name: 'Double Fire',
    category: 'reaction',
    family: 'weather-nature',
    variant: 0,
    popularity: 78,
    tags: ['fire', 'flame', 'hot'],
  },
  {
    slug: 'wind-leaf-fall',
    combo: '💨🍂',
    emojis: ['dashing-away', 'fallen-leaf'],
    name: 'Wind Fall',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 76,
    tags: ['wind', 'fall', 'autumn'],
  },
  {
    slug: 'rain-cloud-sad',
    combo: '🌧️😢',
    emojis: ['cloud-with-rain', 'crying-face'],
    name: 'Rain Sad',
    category: 'emotion',
    family: 'weather-nature',
    variant: 2,
    popularity: 79,
    tags: ['rain', 'sad', 'blue'],
  },
  {
    slug: 'sunflower-bee-spring',
    combo: '🌻🐝',
    emojis: ['sunflower', 'bee'],
    name: 'Sunflower Bee',
    category: 'other',
    family: 'weather-nature',
    variant: 0,
    popularity: 80,
    tags: ['sunflower', 'bee', 'spring'],
  },
  {
    slug: 'rose-love-heart',
    combo: '🌹❤️',
    emojis: ['rose', 'red-heart'],
    name: 'Rose Love',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 84,
    tags: ['rose', 'love', 'romance'],
  },
  {
    slug: 'tulip-spring',
    combo: '🌷🌸',
    emojis: ['tulip', 'cherry-blossom'],
    name: 'Tulip Blossom',
    category: 'emotion',
    family: 'weather-nature',
    variant: 2,
    popularity: 79,
    tags: ['tulip', 'spring', 'bloom'],
  },
  {
    slug: 'mushroom-snail',
    combo: '🍄🐌',
    emojis: ['mushroom', 'snail'],
    name: 'Mushroom Snail',
    category: 'humor',
    family: 'weather-nature',
    variant: 0,
    popularity: 74,
    tags: ['mushroom', 'snail', 'forest'],
  },
  {
    slug: 'fallen-leaf-autumn',
    combo: '🍂🍁',
    emojis: ['fallen-leaf', 'maple-leaf'],
    name: 'Fall Leaves',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 78,
    tags: ['fall', 'leaves', 'autumn'],
  },
  {
    slug: 'comet-night-sky',
    combo: '☄️🌃',
    emojis: ['comet', 'night-sky'],
    name: 'Comet Night',
    category: 'other',
    family: 'weather-nature',
    variant: 2,
    popularity: 73,
    tags: ['comet', 'night', 'sky'],
  },
  {
    slug: 'ringed-planet-rocket',
    combo: '🪐🚀',
    emojis: ['ringed-planet', 'rocket'],
    name: 'Planet Rocket',
    category: 'humor',
    family: 'weather-nature',
    variant: 0,
    popularity: 76,
    tags: ['planet', 'rocket', 'space'],
  },
  {
    slug: 'rainbow-sparkles',
    combo: '🌈✨',
    emojis: ['rainbow', 'sparkles'],
    name: 'Rainbow Sparkle',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 79,
    tags: ['rainbow', 'sparkle', 'magic'],
  },
  {
    slug: 'full-moon-wolf',
    combo: '🌕🐺',
    emojis: ['full-moon', 'wolf-face'],
    name: 'Full Moon Wolf',
    category: 'sarcasm',
    family: 'weather-nature',
    variant: 2,
    popularity: 76,
    tags: ['moon', 'wolf', 'howl'],
  },
  {
    slug: 'sun-behind-rain-cloud',
    combo: '🌦️😎',
    emojis: ['sun-behind-rain-cloud', 'smiling-face-with-sunglasses'],
    name: 'Sun Rain Cool',
    category: 'sarcasm',
    family: 'weather-nature',
    variant: 0,
    popularity: 75,
    tags: ['sun', 'rain', 'unbothered'],
  },
  {
    slug: 'snow-capped-mountain-cold',
    combo: '🏔️🥶',
    emojis: ['snow-capped-mountain', 'cold-face'],
    name: 'Mountain Cold',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 76,
    tags: ['mountain', 'cold', 'freeze'],
  },
  {
    slug: 'rainbow-cloud-sparkles',
    combo: '🌈☁️✨',
    emojis: ['rainbow', 'cloud', 'sparkles'],
    name: 'Rainbow Cloud Sparkle',
    category: 'other',
    family: 'weather-nature',
    variant: 2,
    popularity: 78,
    tags: ['rainbow', 'cloud', 'magic'],
  },
  {
    slug: 'sun-behind-cloud-eye-roll',
    combo: '⛅🙄',
    emojis: ['sun-behind-cloud', 'face-with-rolling-eyes'],
    name: 'Cloud Eye Roll',
    category: 'sarcasm',
    family: 'weather-nature',
    variant: 0,
    popularity: 75,
    tags: ['cloud', 'eye-roll', 'meh'],
  },
  {
    slug: 'fire-warm-thanks',
    combo: '🔥🤲',
    emojis: ['fire', 'palms-up-together'],
    name: 'Warm Hands',
    category: 'emotion',
    family: 'weather-nature',
    variant: 1,
    popularity: 74,
    tags: ['warm', 'fire', 'comfort'],
  },
  {
    slug: 'lightning-bolt-storm',
    combo: '⚡🌩',
    emojis: ['high-voltage', 'cloud-with-lightning-emoji'],
    name: 'Lightning Storm',
    category: 'reaction',
    family: 'weather-nature',
    variant: 2,
    popularity: 76,
    tags: ['lightning', 'storm', 'boom'],
  },
  {
    slug: 'crescent-moon-star-night',
    combo: '🌙⭐',
    emojis: ['crescent-moon', 'star'],
    name: 'Moon Star Night',
    category: 'emotion',
    family: 'weather-nature',
    variant: 0,
    popularity: 80,
    tags: ['moon', 'star', 'night'],
  },
  {
    slug: 'snowman-cold-emoji',
    combo: '⛄🥶',
    emojis: ['snowman', 'cold-face'],
    name: 'Snowman Cold',
    category: 'humor',
    family: 'weather-nature',
    variant: 1,
    popularity: 76,
    tags: ['snowman', 'cold', 'winter'],
  },
  {
    slug: 'leaf-fluttering-wind',
    combo: '🍃💨',
    emojis: ['leaf-fluttering-in-wind', 'dashing-away'],
    name: 'Leaf Wind',
    category: 'other',
    family: 'weather-nature',
    variant: 2,
    popularity: 75,
    tags: ['leaf', 'wind', 'flutter'],
  },
  {
    slug: 'sun-behind-rain-cloud-sad',
    combo: '🌦️😔',
    emojis: ['sun-behind-rain-cloud', 'pensive'],
    name: 'Rain Pensive',
    category: 'emotion',
    family: 'weather-nature',
    variant: 0,
    popularity: 74,
    tags: ['rain', 'pensive', 'blue'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 9: Objects, Tools & Tech — 25 combos
  //   work 22 / reaction 2 / other 1
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'laptop-coffee',
    combo: '💻☕',
    emojis: ['laptop', 'hot-beverage'],
    name: 'Laptop Coffee',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 88,
    tags: ['work', 'coffee', 'laptop'],
  },
  {
    slug: 'briefcase-fire',
    combo: '💼🔥',
    emojis: ['briefcase', 'fire'],
    name: 'Briefcase Fire',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 82,
    tags: ['work', 'briefcase', 'fire'],
  },
  {
    slug: 'rocket-launch',
    combo: '🚀🚀',
    emojis: ['rocket', 'rocket'],
    name: 'Rocket Double',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 80,
    tags: ['launch', 'rocket', 'ship'],
  },
  {
    slug: 'memo-pencil',
    combo: '📝✏️',
    emojis: ['memo', 'pencil'],
    name: 'Memo Pencil',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 79,
    tags: ['note', 'pencil', 'write'],
  },
  {
    slug: 'chart-up-trend',
    combo: '📈📊',
    emojis: ['chart-increasing', 'bar-chart'],
    name: 'Chart Up Trend',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 81,
    tags: ['growth', 'chart', 'trend'],
  },
  {
    slug: 'email-check-mark',
    combo: '📧✅',
    emojis: ['e-mail', 'check-mark-button'],
    name: 'Email Check',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 78,
    tags: ['email', 'inbox', 'done'],
  },
  {
    slug: 'calendar-check-mark',
    combo: '📅✅',
    emojis: ['calendar', 'check-mark-button'],
    name: 'Calendar Done',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 80,
    tags: ['calendar', 'plan', 'done'],
  },
  {
    slug: 'gear-fire',
    combo: '⚙️🔥',
    emojis: ['gear', 'fire'],
    name: 'Gear Fire',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 79,
    tags: ['gear', 'fire', 'engineer'],
  },
  {
    slug: 'mobile-phone-mail',
    combo: '📱📧',
    emojis: ['mobile-phone', 'e-mail'],
    name: 'Phone Mail',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 77,
    tags: ['phone', 'mail', 'comm'],
  },
  {
    slug: 'lightbulb-lightbulb',
    combo: '💡💡',
    emojis: ['light-bulb', 'light-bulb'],
    name: 'Double Idea',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 78,
    tags: ['idea', 'lightbulb', 'eureka'],
  },
  {
    slug: 'alarm-clock-fire',
    combo: '⏰🔥',
    emojis: ['alarm-clock', 'fire'],
    name: 'Alarm Fire',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 77,
    tags: ['alarm', 'urgent', 'fire'],
  },
  {
    slug: 'trophy-briefcase',
    combo: '🏆💼',
    emojis: ['trophy', 'briefcase'],
    name: 'Trophy Briefcase',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 79,
    tags: ['win', 'work', 'trophy'],
  },
  {
    slug: 'laptop-rocket-launch',
    combo: '💻🚀',
    emojis: ['laptop', 'rocket'],
    name: 'Laptop Launch',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 80,
    tags: ['launch', 'laptop', 'ship'],
  },
  {
    slug: 'money-bag-fire',
    combo: '💰🔥',
    emojis: ['money-bag', 'fire'],
    name: 'Money Fire',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 81,
    tags: ['money', 'fire', 'sales'],
  },
  {
    slug: 'pencil-paper',
    combo: '✏️📄',
    emojis: ['pencil', 'page-facing-up'],
    name: 'Pencil Paper',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 76,
    tags: ['pencil', 'paper', 'draft'],
  },
  {
    slug: 'bullseye-target',
    combo: '🎯🎯',
    emojis: ['bullseye', 'bullseye'],
    name: 'Double Bullseye',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 75,
    tags: ['target', 'aim', 'goal'],
  },
  {
    slug: 'gear-gear',
    combo: '⚙️⚙️',
    emojis: ['gear', 'gear'],
    name: 'Double Gear',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 73,
    tags: ['gear', 'cog', 'build'],
  },
  {
    slug: 'clipboard-check',
    combo: '📋✅',
    emojis: ['clipboard', 'check-mark-button'],
    name: 'Clipboard Check',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 77,
    tags: ['clipboard', 'list', 'done'],
  },
  {
    slug: 'briefcase-coffee',
    combo: '💼☕',
    emojis: ['briefcase', 'hot-beverage'],
    name: 'Briefcase Coffee',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 80,
    tags: ['work', 'briefcase', 'coffee'],
  },
  {
    slug: 'hammer-wrench',
    combo: '🔨🔧',
    emojis: ['hammer', 'wrench'],
    name: 'Hammer Wrench',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 78,
    tags: ['tool', 'fix', 'build'],
  },
  {
    slug: 'money-with-wings-chart',
    combo: '💸📈',
    emojis: ['money-with-wings-emoji', 'chart-increasing'],
    name: 'Spend Chart',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 76,
    tags: ['spend', 'chart', 'loss'],
  },
  {
    slug: 'rocket-star',
    combo: '🚀⭐',
    emojis: ['rocket', 'star'],
    name: 'Rocket Star',
    category: 'work',
    family: 'objects-tech',
    variant: 0,
    popularity: 78,
    tags: ['rocket', 'star', 'launch'],
  },
  {
    slug: 'envelope-check',
    combo: '✉️✅',
    emojis: ['envelope', 'check-mark-button'],
    name: 'Mail Sent',
    category: 'work',
    family: 'objects-tech',
    variant: 1,
    popularity: 76,
    tags: ['mail', 'sent', 'inbox'],
  },
  {
    slug: 'bar-chart-fire',
    combo: '📊🔥',
    emojis: ['bar-chart', 'fire'],
    name: 'Chart Fire',
    category: 'work',
    family: 'objects-tech',
    variant: 2,
    popularity: 78,
    tags: ['chart', 'fire', 'growth'],
  },
  {
    slug: 'pin-thumbtack',
    combo: '📌📌',
    emojis: ['pushpin', 'pushpin'],
    name: 'Double Pin',
    category: 'reaction',
    family: 'objects-tech',
    variant: 0,
    popularity: 72,
    tags: ['pin', 'push', 'note'],
  },

  // ──────────────────────────────────────────────────────────────────
  // FAMILY 10: Symbols, Sparkles & Effects — 25 combos
  //   celebration 8 / sarcasm 6 / humor 6 / emotion 5
  // ──────────────────────────────────────────────────────────────────
  {
    slug: 'sparkles-star-glow',
    combo: '✨🌟',
    emojis: ['sparkles', 'glowing-star'],
    name: 'Sparkle Star',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 0,
    popularity: 85,
    tags: ['sparkle', 'star', 'glow'],
  },
  {
    slug: 'fire-100-real',
    combo: '🔥💯',
    emojis: ['fire', 'hundred-points'],
    name: 'Fire 100',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 1,
    popularity: 88,
    tags: ['fire', 'real', 'hype'],
  },
  {
    slug: 'sparkler-firework',
    combo: '🎇🎆',
    emojis: ['sparkler', 'fireworks'],
    name: 'Sparkler Firework',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 2,
    popularity: 82,
    tags: ['sparkler', 'firework', 'nye'],
  },
  {
    slug: 'collision-bomb',
    combo: '💥💣',
    emojis: ['collision', 'bomb'],
    name: 'Boom Bomb',
    category: 'reaction',
    family: 'symbols-effects',
    variant: 0,
    popularity: 80,
    tags: ['boom', 'explode', 'drama'],
  },
  {
    slug: 'high-voltage-sparkles',
    combo: '⚡✨',
    emojis: ['high-voltage', 'sparkles'],
    name: 'Bolt Sparkle',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 1,
    popularity: 81,
    tags: ['bolt', 'sparkle', 'electric'],
  },
  {
    slug: 'anger-symbol-anger-symbol',
    combo: '💢💢',
    emojis: ['anger-symbol', 'anger-symbol'],
    name: 'Double Anger',
    category: 'sarcasm',
    family: 'symbols-effects',
    variant: 2,
    popularity: 73,
    tags: ['anger', 'mad', 'furious'],
  },
  {
    slug: 'warning-stop',
    combo: '⚠️🛑',
    emojis: ['warning', 'stop-sign'],
    name: 'Warning Stop',
    category: 'sarcasm',
    family: 'symbols-effects',
    variant: 0,
    popularity: 76,
    tags: ['warning', 'stop', 'careful'],
  },
  {
    slug: 'check-mark-sparkles',
    combo: '✅✨',
    emojis: ['check-mark-button', 'sparkles'],
    name: 'Check Sparkle',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 1,
    popularity: 79,
    tags: ['check', 'sparkle', 'done'],
  },
  {
    slug: 'cross-mark-eye-roll',
    combo: '❌🙄',
    emojis: ['cross-mark', 'face-with-rolling-eyes'],
    name: 'Cross Eye Roll',
    category: 'sarcasm',
    family: 'symbols-effects',
    variant: 2,
    popularity: 76,
    tags: ['no', 'eye-roll', 'reject'],
  },
  {
    slug: 'question-mark-thinking',
    combo: '❓🤔',
    emojis: ['question-mark', 'thinking-face'],
    name: 'Question Think',
    category: 'reaction',
    family: 'symbols-effects',
    variant: 0,
    popularity: 77,
    tags: ['question', 'think', 'why'],
  },
  {
    slug: 'exclamation-mark-fire',
    combo: '❗🔥',
    emojis: ['exclamation-mark', 'fire'],
    name: 'Exclaim Fire',
    category: 'humor',
    family: 'symbols-effects',
    variant: 1,
    popularity: 78,
    tags: ['bang', 'fire', 'urgent'],
  },
  {
    slug: 'heart-exclamation-100',
    combo: '❣️💯',
    emojis: ['heart-exclamation', 'hundred-points'],
    name: 'Heart Exclaim Real',
    category: 'emotion',
    family: 'symbols-effects',
    variant: 2,
    popularity: 80,
    tags: ['heart', 'exclaim', 'real'],
  },
  {
    slug: 'musical-notes-sparkles',
    combo: '🎶✨',
    emojis: ['musical-notes', 'sparkles'],
    name: 'Music Sparkle',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 0,
    popularity: 80,
    tags: ['music', 'sparkle', 'vibe'],
  },
  {
    slug: 'infinity-sparkles',
    combo: '♾️✨',
    emojis: ['infinity', 'sparkles'],
    name: 'Infinity Sparkle',
    category: 'emotion',
    family: 'symbols-effects',
    variant: 1,
    popularity: 78,
    tags: ['infinity', 'sparkle', 'forever'],
  },
  {
    slug: 'peace-symbol-yin-yang',
    combo: '☮️☯️',
    emojis: ['peace-symbol', 'yin-yang'],
    name: 'Peace Yin Yang',
    category: 'emotion',
    family: 'symbols-effects',
    variant: 2,
    popularity: 76,
    tags: ['peace', 'balance', 'zen'],
  },
  {
    slug: 'star-of-david-star',
    combo: '✡️⭐',
    emojis: ['star-of-david', 'star'],
    name: 'Star Star',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 0,
    popularity: 74,
    tags: ['star', 'jewish', 'shine'],
  },
  {
    slug: 'atom-symbol-sparkles',
    combo: '⚛️✨',
    emojis: ['atom-symbol', 'sparkles'],
    name: 'Atom Sparkle',
    category: 'humor',
    family: 'symbols-effects',
    variant: 1,
    popularity: 75,
    tags: ['atom', 'science', 'sparkle'],
  },
  {
    slug: '100-check-mark',
    combo: '💯✅',
    emojis: ['hundred-points', 'check-mark-button'],
    name: 'Real Check',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 2,
    popularity: 79,
    tags: ['real', 'check', 'confirm'],
  },
  {
    slug: 'zzz-sleeping',
    combo: '💤😴',
    emojis: ['zzz', 'sleeping-face'],
    name: 'Zzz Sleep',
    category: 'humor',
    family: 'symbols-effects',
    variant: 0,
    popularity: 78,
    tags: ['sleep', 'zzz', 'rest'],
  },
  {
    slug: 'sweat-droplets-water',
    combo: '💦💧',
    emojis: ['sweat-droplets', 'droplet'],
    name: 'Double Drop',
    category: 'humor',
    family: 'symbols-effects',
    variant: 1,
    popularity: 74,
    tags: ['water', 'drop', 'sweat'],
  },
  {
    slug: 'dashing-away-wind',
    combo: '💨💨',
    emojis: ['dashing-away', 'dashing-away'],
    name: 'Double Wind',
    category: 'humor',
    family: 'symbols-effects',
    variant: 2,
    popularity: 72,
    tags: ['wind', 'fast', 'go'],
  },
  {
    slug: 'speech-balloon-heart',
    combo: '💬❤️',
    emojis: ['speech-balloon', 'red-heart'],
    name: 'Message Love',
    category: 'emotion',
    family: 'symbols-effects',
    variant: 0,
    popularity: 78,
    tags: ['chat', 'love', 'message'],
  },
  {
    slug: 'thought-balloon-question',
    combo: '💭❓',
    emojis: ['thought-balloon', 'question-mark'],
    name: 'Thought Question',
    category: 'sarcasm',
    family: 'symbols-effects',
    variant: 1,
    popularity: 76,
    tags: ['think', 'question', 'wonder'],
  },
  {
    slug: 'star-sparkles-100',
    combo: '⭐✨💯',
    emojis: ['star', 'sparkles', 'hundred-points'],
    name: 'Star Sparkle Real',
    category: 'celebration',
    family: 'symbols-effects',
    variant: 2,
    popularity: 80,
    tags: ['star', 'sparkle', 'real'],
  },
  {
    slug: 'cross-mark-skull',
    combo: '❌💀',
    emojis: ['cross-mark', 'skull'],
    name: 'Cross Skull',
    category: 'sarcasm',
    family: 'symbols-effects',
    variant: 0,
    popularity: 76,
    tags: ['no', 'dead', 'savage'],
  },
];

// --- Sanity checks ---
const seen = new Set<string>();
for (const e of PLAN) {
  if (existingSlugs.has(e.slug)) throw new Error(`collision with existing combo: ${e.slug}`);
  if (seen.has(e.slug)) throw new Error(`internal duplicate: ${e.slug}`);
  seen.add(e.slug);
}
if (PLAN.length !== 250) throw new Error(`expected 250, got ${PLAN.length}`);

// --- Bucket by family for commit + PR groupings ---
const byFamily = PLAN.reduce<Record<string, ComboPlanEntry[]>>((acc, e) => {
  (acc[e.family] ??= []).push(e);
  return acc;
}, {});

for (const [fam, list] of Object.entries(byFamily)) {
  if (list.length !== 25) throw new Error(`${fam} has ${list.length}, expected 25`);
}

// --- Persist as JSON for the generator to consume ---
const out: Record<string, ComboPlanEntry[]> = byFamily;
fs.writeFileSync(
  path.join(process.cwd(), 'scripts', 'batch-23-32-plan.json'),
  JSON.stringify(out, null, 2)
);
console.log('Plan written. Families:');
for (const [fam, list] of Object.entries(byFamily)) {
  console.log(`  ${fam}: ${list.length}`);
}
